# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ben Ludwig
email: ben.tyler.ludwig@gmail.com
description: The work of Ben Ludwig.
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  benludwig
permalink: pretty
google_analytics: UA-156252964-1

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Collections
collections_dir: content
collections:
  articles:
    output: true
  case-studies:
    output: true
  design-work:
    output: true
  just-for-fun:
    output: true
  side-projects:
    output: true
  design:
    output: true
  other:
    output: true
